language: generic

services:
  - docker

jobs:
  include:
    - stage: "Unit Tests"
      before_script:
        - docker build -f ./build/docker-ci/Dockerfile . -t gotorrent-ci
      script:
        - docker run gotorrent-ci
    - stage: "Integration Tests"
      name: "Test Download 1"
      before_script:
        - ./scripts/test/build_dockers.sh
      script:
        - ./scripts/test/test_download_1.sh
    - name: "Test Download 2"
      before_script:
        - ./scripts/test/build_dockers.sh
      script:
        - ./scripts/test/test_download_2.sh
    - name: "Test Download Upload 1"
      before_script:
        - ./scripts/test/build_dockers.sh
      script:
        - ./scripts/test/test_download_upload_1.sh
    - name: "Test Download Upload 2"
      before_script:
        - ./scripts/test/build_dockers.sh
      script:
        - ./scripts/test/test_download_upload_2.sh